[package]
name = "chinese-name-meaning-explorer"
version = "0.1.7"
description = "A Chinese Name Meaning Explorer with internal LLM"
authors = ["Qingyang Mei"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10.9"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["stream"] }
futures-util = "0.3"
dirs = "5.0"
fs2 = "0.4"
encoding_rs = "0.8.35"
llama-cpp-2 = { version = "=0.1.152", default-features = false }
sysinfo = "0.30"
tauri-plugin-shell = "2.0.0"
tauri-plugin-opener = "2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Storage_FileSystem"] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
